### ISSUE TITLE
Synch Local Time zone in Web gui

### ISSUE THREAD

**Issue by smportis** [taniman/proxy-bot#100]
I would like to be able to specify the local time zone in the prefs so that the web gui will display the same time as my local trades in the Logs.

**Comment by taniman** [comment]
New version will have timezone offset setting. hopefully this helps

**Comment by YoJeff** [comment]
Just store the date in ISO format so it's easily consumable.    Timezones are a frontend issue.

**Comment by taniman** [comment]
hmmmm. all dates are currently send to frontend as EXCHANGE timezone. The format is maybe not easy, but it's parseable. (Dont wanna break DJ's gui now). So not gonna change it to iso now.  
The new setting will change this behaviour a bit true. But if people dont set it. The time is EXCHANGE time.

**Comment by smportis** [comment]
That works!
