### ISSUE TITLE
Enhancement: Option to show "all sells" in web gui instead of just last 24(?) hours 

### ISSUE THREAD

**Issue by smportis** [taniman/proxy-bot#101]
it would be nice to be able to hit a button or checkbox and have all trades displayed instead of just the past 24 hours as is the current setting.

**Comment by taniman** [comment]
Not sure if you know this, but the sell log contains only values that the bot sold. And it is currently the data in ProxyData.json 
I guess it is possible to show more than just the last 24 hours.  But We dont want to log file to grow too big

**Comment by smportis** [comment]
I hear you on the size concerns, however since 24 hours is only 14KB, it might be able to be stretched for 2 weeks, depending on the ability of the program to parse that much log data efficiently.

**Comment by YoJeff** [comment]
If you are concerned about size, make it a seperate endpoint.   So when you poll for stats you aren't repulling 100 sales over and over.
