### ISSUE TITLE
buy_fillOrKill option

### ISSUE THREAD

**Issue by Anderson-PB** [taniman/proxy-bot#111]
If buy_fillOrKill = true 
DCA Counter doesn't work on Anderson DCA Strategy.

Turned it on, make 4 dca buys no counts, i turned it off, made one and counter worked fine.

**Comment by taniman** [comment]
fillorkill does not work with trex api. found other reports about this. So we will need to think of something else for trex and anderson strategy

**Comment by Anderson-PB** [comment]
As we talked on tg... Order book :)
