### ISSUE TITLE
Feature: EMASPREAD as DCA buy trigger

### ISSUE THREAD

**Issue by Helmi** [taniman/proxy-bot#115]
Implement EMASPREAD basically as it is described in the Wiki to be used as a DCA strategy.

This could be used to buy only on uptrends (faster EMA is above slower EMA) or rather on a specified spread of this situation.

It should of course be combined with the buy_trigger to set a minimum loss for the DCA buy.

**Comment by taniman** [comment]
First implementation. Will beautify it on next release according to comments
