### ISSUE TITLE
DCA.properties new properties

### ISSUE THREAD

**Issue by taniman** [taniman/proxy-bot#122]
~~ignore_consecutive_buys~~
~~ignore_price_drop~~
~~ignore_price_rice~~
~~allow_stop_loss~~
~~allow_pending_orders~~
~~ignore_sell_only_mode~~
~~seperate trialing_proft and buy?~~

**Comment by scoutband** [comment]
Would be useful if possible an opiton to put normal pairs into DCA state after a % of loss is reached as described in the issue #119
