### ISSUE TITLE
Feature: DCA min buy volume

### ISSUE THREAD

**Issue by Helmi** [taniman/proxy-bot#127]
When trading low volumes with 0.0005 or similar initial purchase there's a good chance when coin value drops the BTC value drops below min Bittrex Trading volume of 0.0005 BTC (50k Satoshi). 

If that happens DCA buys won't succeed as they try to buy 0.00049 or lower which won't work.

Therefore it would be great to set a minimal DCA buy volume which we could then set to 0.0005 or whatever the exchange forces us to set it to and would be able to have successful DCA buys again.

**Comment by taniman** [comment]
I think I know now why this is happening. you have disabled hideDust feature right? In configuration.properties.
If hidedust is enabled than this coin will only DCA when there is enough volume. So there is no need to create a new setting
