### ISSUE TITLE
Small Fix: Revert Sell Log numbering

### ISSUE THREAD

**Issue by Helmi** [taniman/proxy-bot#128]
I think it would make more sense if the numbers in the sell log were somehow persistant and won't change whenever a new one comes in. That would also make copying to excel for quick analysis easier if you could just copy over new trades with new numbers instead of having the old ones renumbered every time.

So I would pledge for #1 for the first Trade in the records and counting up from there.

**Comment by taniman** [comment]
I hope the new gui with sorting can help with this. But other than that I do not see a huge reason to work on this one.
