### ISSUE TITLE
GUI Feature Request

### ISSUE THREAD

**Issue by JReich82** [taniman/proxy-bot#130]
Create links, or buttons built into GUI for the 3 types of manual overrides.

Add a section, or some sort of notification system in the GUI for error logs.

Add start and stop buttons.

Make configs configurable from the GUI.

And fyi, nice work with this whole project. Its coming along nicely, thanks for your hard work and dedication.

**Comment by taniman** [comment]
The intention is to normally create 1 issue per feature request.  This issue is requesting too much at the same time

**Comment by JReich82** [comment]
Sorry about that.  I will fix when the wife gives me more than 2 minutes to sit down...
