### ISSUE TITLE
Version Control in properties files

### ISSUE THREAD

**Issue by smportis** [taniman/proxy-bot#139]
For the love of all that is sweet and holy, please put some version control comments in the "properties" files going forward. It is hell trying to decipher what you've added and what you have changed in these files. 

Something like this:
```
################## pairs.properties ###################
################### VERSION CONTROL ###################
#######################################################
### OCT 15, 2017 Added ALL_min_buy_price - the minimum price below which .....
### OCT 14, 2017 Added ALL_max_buy_spread - max spread % between lowest ask ...
### etc, etc, 
#######################################################
#######################################################
```

**Comment by taniman** [comment]
hey, that's a great idea. But guaranteed I will forget to add it! would you be happy with the same but on a wiki page? The change log for properties wiki page?

**Comment by minerdude** [comment]
Elroy someday you will need a dev and support staff hehe

**Comment by taniman** [comment]
Yeah, when i can afford a staff I will post a request.  :D

**Comment by smportis** [comment]
Yes, that would be a great 2nd best option. Having it in both locations would be best. 

Seems like it would be harder to maintain the wiki page than the actual file itself, but making sure the wiki has the info is the most important thing, long term. 

I tend to add documentation to my properties files so that I know what all the variables do, so when you add things, and mine are out of order of yours, it is hard to integrate the changes into the file. 

Even if you just put comments around the new items in the config files it would help!

**Comment by smportis** [comment]
All right Elroy!! You put it in configuration.properties!! Thank you!! 
Only 4 more files to go!
This is already very helpful. 

Reminder to toss it into application.prop to denote the change to server.timezoneoffset

**Comment by taniman** [comment]
done.
