### ISSUE TITLE
forgot bought price

### ISSUE THREAD

**Issue by JReich82** [taniman/proxy-bot#143]
dca bought a coin, then immediately forgot the average buy price. 
I get please set average bought price fairly often. Not necessarily always with dca...

0|proxy-bo | 2017-10-17 02:57:35 INFO DCAStrategyRunner - DCA - LOWBB bought -- currency pair BTC-ADA - current profit -12.271
0|proxy-bo | 2017-10-17 02:57 -04:00: 2017-10-17 02:57:42 WARN AverageCalculator - Please set BTC-ADA_bought_price

**Comment by taniman** [comment]
#124
