### ISSUE TITLE
Invalid license pm2 infinite loop

### ISSUE THREAD

**Issue by taniman** [taniman/proxy-bot#150]

**Comment by minerdude** [comment]
already got this error running with sudo and port 443, and only with pm2

**Comment by taniman** [comment]
I have updated the pm2-ProxyBot.json file to not allow auto-restarts. this fixed this problem when using pm2

**Comment by rlorenzo316** [comment]
When trying to run the bot I keep getting an invalid license. I have been trying to trouble shoot the problem for the last two days NOTHING works!

The only thing I can think of is I tried running it on my MacBook bro and iMac and neither of them worked. So now I'm running it on my ASUS windows. Maybe having the files on multiple laptops is a problem?

Please help
