### ISSUE TITLE
password protect pages

### ISSUE THREAD

**Issue by taniman** [taniman/proxy-bot#54]

**Comment by scoutband** [comment]
and https support due to the fact that exposed monitoring page throught public ip is in clear and someone can be read content of BTC in "Totals log" page

**Comment by cryptowally** [comment]
Definitely would prefer to have https support and some sort of authentication.  For VPS users, as soon as the proxy is installed and premium features turned on, all people have to do is scan for port 8081 and they will immediately see this unless they put iptables or some other type of basic firewall protection on.

**Comment by taniman** [comment]
@cryptowally it is possible to not expose the ip to the internet by changing bind address
Also port 443 is always there if people need some encryption
Only thing is that visiting https://locahost/monitoring will return an error message. But with the correct SSL certificate setup it should work,

**Comment by Helmi** [comment]
on the long run some integration with https://certbot.eff.org/ and at least some basic auth would be good.

**Comment by vr0** [comment]
I use Premium Proxybot with Caddy:

`application.properties`
```
server.port = 65080
server.additionalPort = 65081
```

`/etc/caddy/Caddyfile` (default use Let's Encrypt)

```
https://your.domain.tld {
basicauth / USERNAME PASSWORD
proxy / localhost:65081 {
  websocket
  transparent
  }
}
```
`iptables setup`

```
iptables -I INPUT -p tcp -s 127.0.0.1 --dport 65080 -j ACCEPT
iptables -I INPUT -p tcp -s 127.0.0.1 --dport 65081 -j ACCEPT
iptables -A INPUT -p tcp --dport 65080 -j DROP
iptables -A INPUT -p tcp --dport 65081 -j DROP
```

And it works like a charm.

Kind regards,
vr0
