### ISSUE TITLE
Monitor Enhancement: Sorting By Column

### ISSUE THREAD

**Issue by lenardbang** [taniman/proxy-bot#59]
Ability to sort views, by columns ascending/descending

**Comment by taniman** [comment]
Due to the fact that the page refreshes every few seconds, I will have to do some front end logic for this. Maybe dj_crypto can look into this.

**Comment by jadiesel** [comment]
It might be  better to look at building this page out with css and javascript - we can lose the screen refresh and then have a gui platform to build on to. Maybe bundle the gui up as a node app (just thinking out loud.)

**Comment by YoJeff** [comment]
json api endpoint(s),  then we can have many flavors.

**Comment by taniman** [comment]
I have created a /monitoring/data which is returning the data in json format. 
It's actually the same data that is save in ProxyBotData.json. 

So hopefully this will help with building some nice stuff

**Comment by gmjosund** [comment]
All is in progress, creating a new monitor.

**Comment by lenardbang** [comment]
Would be cool, to have as much information as possible on single page in my opinion, instead of jumping around, to see for example the totals log and what not. good luck, cant wait to see new version!
