### ISSUE TITLE
Stop Loss

### ISSUE THREAD

**Issue by YoJeff** [taniman/proxy-bot#63]
Stop loss option for PB.   Would need to be mutually exclusive with DCA.   Something like...

```
# trigger panic sell when price drops buy x%
ALL_panic_sell_trigger = 10
# disable panic after x minutes
ALL_panic_sell_timeout = 10
```

The timeout does not need to necessarily be time based.   Just something to pause trading after a panic, primarily to prevent buy/stop loops.

**Comment by PutraBit88** [comment]
Hi,
do you have any idea how for STOP BUY? my problem now is I'm setting my buy strategy very tight which EMASPREAD 1% with SMA1=3, SMA2=1. So far it perform very well as i made rebuy from same coin 3times in less than 10min with 6% profit. But the problem my bot still keep buying for the 4rd times which unfortunately while the price became lower and lower which finally end up in DCA with high negative %. 

So, is there anyway that i can avoid from my bot to buy at the time when the price getting lower, any option that i can set to stop buy at certain limit? below is my setting.


ALL_buy_strategy = EMASPREAD
ALL_buy_value = 1

EMA_period = 900
EMA_1 = 3
EMA_2 = 1

**Comment by Sereglaith** [comment]
The new version has a rebuy timeout, which would be helpful in your described case.  I would also recommend setting a _buy_value_limit.  In addition, you could also try EMACROSS instead.

**Comment by PutraBit88** [comment]
Thanks for quick feedback,  I'm trying with below setting..

ALL_buy_strategy = EMASPREAD
ALL_buy_value = 0.8
ALL_trailing_buy = 0.5
ALL_buy_order_wait_time = 3

**Comment by SgtBatten** [comment]
Trailing doesn't work for positive buy values as that wouldn't make sense.

Also buy order wait time I don't believe is a real parameter.

**Comment by PutraBit88** [comment]
Thanks for the correction, i will try this one, i will see if the wait time is working or not

ALL_buy_strategy = EMASPREAD
#This is the value that your indicator has to hit before the bot decides to buy
#In this case the bot waits for the price be below 1% upper EMASPREAD
ALL_buy_value = 1
#ALL _buy_value_limit = 1.5
#ALL_trailing_buy = 0.3
ALL_buy_order_wait_time = 1

**Comment by PutraBit88** [comment]
I try with another setting but seems my order is not fill, is there any wrong for below buy setting?

ALL_buy_strategy = EMACROSS
EMA_cross_candles = 1
ALL_buy_value = 0.5

EMA_period = 900
#Slow
EMA_1 = 3
#Fast
EMA_2 = 1
