### ISSUE TITLE
technical indicators : bollinger_band_width

### ISSUE THREAD

**Issue by dechut** [taniman/proxy-bot#77]
Hi everyone .

I have a suggestion for buy condition : bollinger_band_width .

bollinger_band_width = (highbb - lowbb) / middle line .

if bollinger_band_width < X% then dont buy .

recommend : 3% for new trade . and 5% for DCA .

 ( in theory it can be 1% , but nobody can buy at very bottom and sell in top ) .

this mean : we only trade with active pair , and clear bag when pair become more active .

**Comment by m59peacemaker** [comment]
This seems essential for BB strategy. Is it not going to happen?
