### ISSUE TITLE
[Monitor] Add dynamic tables

### ISSUE THREAD

**Issue by Helmi** [taniman/proxy-bot#90]
adding some more dynamic tables to the monitor could help getting a better overview of what's happening. As you are already using jQuery in the monitor there are two great options available:

- https://datatables.net/
- https://www.dynatable.com/

Both are open source, the first one is a bit more popular and well known. They should allow you to feed data via json. This would make it easily possible to change the sorting of the tables or apply some filters to the output. Also it should be possible to hide some data by default. User could then toggle the display or something like that.

At least for Datatables there's some Bootstrap 3 styling available so it should be easy to implement without the need of a lot of design work.

**Comment by gmjosund** [comment]
Its already been in the works for some time :)
