### ISSUE TITLE
Wiki Edit: DCA 

### ISSUE THREAD

**Issue by smportis** [taniman/proxy-bot#96]
Suggested changes to DCA Wiki page to be more clear: (if you don't like these suggestions, just ignore them. Just trying to contribute and reduce the same questions over and over)

1. Suggest adding a sentence talking about what dollar cost averaging is. For example:
"Dollar-cost averaging (DCA) is an investment technique of buying a fixed dollar amount of a particular investment on a regular schedule, regardless of the share price. The investor purchases more shares when prices are low and fewer shares when prices are high.

In our case however, we are using it to purchase more shares (coins) to offset a purchase at a high value that later went down in price creating a potential loss (aka a "bag"). "

2. Change this:
The strategy to use to buy more coins.
buy trigger indicates how much loss the coin should have to even think about activating DCA on it.
buy_strategy = HIGHBB
buy_value = 0
buy_trigger = -4

To:
The strategy to use to buy more coins.
buy_trigger indicates how much loss the coin should have *before* activating DCA on it. *buy_value indicates the % above (or below if negative) the buy_strategy to execute the buy. *
buy_strategy = HIGHBB
buy_value = 0
buy_trigger = -4

3. Change this:
Sell my average down coins if they reach a profit of 1%.
sell_strategy = GAIN
sell_value = 0.6

To this:
Sell my average down coins if they reach a profit of *0.6%*
sell_strategy = GAIN
sell_value = 0.6

**Comment by taniman** [comment]
tnx.

**Comment by smportis** [comment]
Didn't quite get this one right: 
Sell my average down coins if they reach a profit of 0.6%.
sell_strategy = GAIN
sell_value = 0.0  **<<<<----- should be 0.6**
